---
language: go

go:
- 1.7

install:
  - mkdir $GOPATH/bin
  - curl https://glide.sh/get | sh
  - glide install
  - go get github.com/golang/lint/golint

script:
  - go test github.com/StarburstComputing/node-discovery
  - golint -set_exit_status github.com/StarburstComputing/node-discovery